language: python

python:
  - "2.7"

env:
  - PORT=8080

cache: pip

install:
  - pip install -r src/requirements.txt
  - pip install -r test/test_requirements.txt

script:
  - pytest

deploy:
  provider: cloudfoundry
  username: TerryWahl
  password:
    secure: JNJBxOPbBICFkAUaotcLAFIDxdFib1zEK8LVGF3T2wQIhR1gKD1nGrsV5b6aczikrl3ZZA6nr40lrAUz8zK3t9dvM29b8pZKvmZokMPYvK15bSV3NcPwe4fXwTfPmERBijlRX327L714dAxv9S1IzXCKeelYpiRU9CU7gZGJX4A99NClfJJ9opMtHFVr8hP5gfM5c+KVF2C3FMO6NCm4ybkGKxNTdzmRpDn1DL8INwa74XD11PeRb83rIxF6WgM71WIb+6d+vDKiwasMhXPy1Dcnh3MR10STykVyN3F3/xkL/MWFtBOwkIpMqD52gvrxFQJS24ql4dHKKvXhchndOVCMisSjc07mFiw9XOTbheuRalaA2UOJIBdzoiMB3dN5abkD9XNR+EPrJw9rFnSL4ExMCpuYMwECJlJGsq/G7bdit1IhtXKZNnEHozP4fPeOGQUca9ZM+LTUzRoTgylxVkW1Mb6LA10gTwt3rEPpgJTC6bWmqtZKg/PKloJgw/oRhrYnvGCCouvL52ee6H4/XighX0FIA+pddURi7o5wTF+ix70SpgWNFTWSNplU+QSHp4tFtdBi28YJH9+2Uj/fGoFnBHcd8iz/SFYfxR9hpvUgRC3xwkMErJ9xkJZVB/CRj7Hx9qiUT+hPTPJYzBu3AP75vR2IDy4LIaeRisN30F0=
  api: https://api.run.pivotal.io
  organization: cc nl
  space: staging
